### ISSUE TITLE
Error detected, Invalid channel "3"

### ISSUE THREAD

**Issue by SevereOverfl0w** [snoe/nvim-parinfer.js#6]
This error seems almost random (race condition?)

But occurs occasionally (and then refuses to go away until I restart neovim)

```
Error detected while processing TextChangedI Auto commands for "*.clj*":
Invalid channel "3"
```

I found this issue, has a similar error: https://github.com/neovim/python-client/issues/80 Might be related?

**Comment by snoe** [comment]
I see this occasionally as well, there is definitely an issue here. I haven't narrowed it down yet but quickly indenting blocks of code (and thus triggering parinfer) seems to trigger it. 

The error is indicative that the node-host client has become disconnected from the editor. Do you see anything of import in your `~/.nvimlog`? I would expect a stack trace to show up there but I haven't caught any indication in there other than the `Invalid channel` error you indicated.

This used to happen more frequently due to a problem in node-host https://github.com/neovim/node-client/issues/8 but that always produced a trace. Make sure your node-host dependencies have `neovim-client@1.0.6` as the installed npm dependency.

**Comment by SevereOverfl0w** [comment]
```
2015/11/25 14:17:29 [error @ forward_stderr:333] 10258 - Channel 1 stderr: Exception ignored in: 
2015/11/25 14:17:29 [error @ call_set_error:743] 10258 - msgpack-rpc: Channel was closed by the client
2015/11/25 14:17:29 [error @ call_set_error:743] 10258 - msgpack-rpc: Channel was closed by the client
```

Pulled from my `~/.nvimlog`. 

`neovim-client` is at `1.0.5` so I'll try bump it up.

**Comment by SevereOverfl0w** [comment]
Jumped into my `~/.nvimlog` straight after seeing the error:

```
2015/11/25 18:37:50 [error @ call_set_error:743] 27499 - msgpack-rpc: Channel was closed by the client
2015/11/25 18:56:21 [error @ call_set_error:743] 27499 - msgpack-rpc: Channel 3 returned a response that doesn't have a matching request id. Ensure the client is properly synchronized
2015/11/25 18:56:21 [error @ call_set_error:743] 27499 - msgpack-rpc: Channel 3 returned a response that doesn't have a matching request id. Ensure the client is properly synchronized
2015/11/25 18:56:21 [error @ call_set_error:743] 27499 - msgpack-rpc: Channel was closed by the client
```

**Comment by snoe** [comment]
I pushed https://github.com/snoe/nvim-parinfer.js/commit/24b257eec791b740a3c0b7279e6ede9ea6700311 because changing from `plugin.commandSync` to `plugin.command` seems to have fixed my repro case for this.

Unfortunately I wasn't able to hone in very well on why this occurred and it may be unresolved. Please update and let me know if you still crash and I'll be doing the same. It does seem related to calling the command to `sync-lines`. I don't think our code is doing anything wrong, but the callback nature of this api IMO is making it difficult to do the right thing. 

I think it would be safest if it was possible to keep the autocommand synchronous and only return once the buffer has been modified. I've spent a long time with core async and es6 generators and I don't see a way forward with either approach.

**Comment by SevereOverfl0w** [comment]
Sorry I've not been back to you sooner, I've not been writing much Clojure!

I haven't seen this error in some time, I have seen some *slightly* delayed triggers, no idea if that's due to this change or not. Such is async though eh?

**Comment by snoe** [comment]
I took a different approach with the latest on master and started doing more work in vimscript, this allows a synchronous approach but has exposed a bug on the neovim side https://github.com/neovim/node-host/issues/6 and required a switch to use a better (faster) diff. In the medium term, hopefully, this will be the best way forward.
